language: go
os:
  - osx
  - linux
  - windows
go:
  - tip
install:
  - go get -v
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];   then sudo apt-get install libpcap-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then sudo apt-get install libpcap-dev; fi
