language: go
os:
  - osx
  - linux
  - windows
go:
  - 1.5
  - 1.6
  - tip
  - 1.7rc5
  - 1.7rc6
install:
 - go get github.com/google/gopacket
 - go get github.com/google/gopacket/layers
 - go get github.com/google/gopacket/tcpassembly
